### ISSUE TITLE
app-text/obsidian bump

### ISSUE THREAD

**Issue by yibaba** [r7l/r7l-overlay#1]
The 0.13.30 version of obsidian has been released (https://obsidian.md/download).
Can you bump the ebuild to the latest version?

Thank you for yout time.

**Comment by r7l** [comment]
@yibaba Thanks for stopping by. I saw their release yesterday as well and was planning to restructure the Ebuild since they've finally managed to put out a new .deb file. But i am lacking of time right now. So i've just updated the versions and kept the current structure. I've tested it and you should be able to update as well. If you're using the overlay from Gentoo mirror, it might take a bit to sync.
