### ISSUE TITLE
net-proxy/traefik/traefik-2.10.4 depends on non-existing nodejs version

### ISSUE THREAD

**Issue by AlexPuchmayr** [r7l/r7l-overlay#7]
BDEPEND=">net-libs/nodejs-13
        <net-libs/nodejs-15"
Lowest version available is nodejs-16.20.2.ebuild, hence the packet cannot  be installed/upgraded anymore.

**Comment by r7l** [comment]
Thanks allot for the report. I am actually aware of the issue but was kinda hoping for upstream to finally move on. But they never did. I still had an Ebuild for NodeJS 14 laying around but i it's not compatible with OpenSSL 3.x and not of much use for this reason. So it has not been added it to the repo. I may have to give NodeJS 16 a try, even if Traefik itself doesn't use it.

**Comment by AlexPuchmayr** [comment]
I also found an outdated nodejs-14.21.1, and there is a combination of useflags for nodejs which at least allows compiling the stuff: 
-system-ssl +ssl

Unfortunately, nodejs-14 does not seem to be compilable with gcc-13 (lots of compile errors), so this is also no option anymore. I think it doesn't make much sense spending time investigating errors on a outdated version of nodejs.

You say Traefik itself doesn't use nodejs? Then why is there this dependency at all?

**Comment by r7l** [comment]
Traefik is using NodeJS in Version 14, as you can see [here](https://github.com/traefik/traefik/blob/master/webui/Dockerfile). They have a Dockerfile to compile the frontend UI. There are basically 3 options from here:

- they'll update to a newer NodeJS version
- the Ebuild uses a different version then upstream
- downloading the binary file and use the compiled UI from there

Being on Gentoo means compiling stuff on our own and that is the main reason for me using NodeJS instead of the compiled binary. At least so far.

I will work on the Ebuild but i can't promise it to be finished today. It's also still using EAPI 7 with `golang-vcs-snapshot`. Both should be replaced as well.

Edit: There is a PR it update NodeJS on upstream. It's untouched since June: https://github.com/traefik/traefik/pull/8107

**Comment by AlexPuchmayr** [comment]
So it seems nodejs is only used for the web-UI, which I personally don't need. 
Would it be an option adding an extra use-flag "web-ui" and hence making it optional, including the dependency to nodejs?

**Comment by r7l** [comment]
I've attempted to fix the issues on the Ebuild today. But it's not as easy as i was hoping. The Ebuild fails for multiple reasons. The NodeJS part seems to be broken. No matter if NodeJS 14 or else. Some of the currently used modules seem missing from NPM and the Go build is also failing. I won't have more time today but i'll try working on it next weekend.

Edit: I am using the Ebuild myself. But since there hasn't been any updates since July, i didn't touch it. It also seems as if Traefik is only working on Version 3 currently. So i don't think we'll see any new version soon. And they still use NodeJS 14 in Traefik version 3.

**Comment by r7l** [comment]
@AlexPuchmayr I've tested a couple things but decided to ship the UI with a custom repo. I've build the UI using their Docker image and pushed it to a repo and the Ebuild will download it from there. I don't see any other way besides removing the UI which seems to cause issues as the build did expect the files.

There was a new version which fixed the build issues with Go. I've just pushed it to my overlay.

If you encounter any additional issues, don't hesistate to report back.

Thanks again for the report.

**Comment by AlexPuchmayr** [comment]
Thank you very much for your effort!
It compiles and seems to work :-)

One thing: In post-install, there should be a "setcap cap_net_bind_service+ep /usr/bin/traefik" added to allow the traefik-user to allow opening port 80, 443 or other privileged ports.
